sonar.projectKey=Lenox30_SHXL-GCS
sonar.organization=lenox30

# Nombre opcional
sonar.projectName=SHXL-GCS

# Rutas del código a analizar (TUS carpetas reales!)
sonar.sources=backend, frontend

# Para Python
sonar.python.version=3.10

# Para JavaScript
sonar.javascript.node.maxspace=4096

# Encoding
sonar.sourceEncoding=UTF-8
